version: '3'

services:
  mysql:
    image: mysql:5.5
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M
      VIRTUAL_HOST: phpmyadmin.backsoul.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: phpmyadmin.backsoul.dev
      LETSENCRYPT_EMAIL: danielsarmientoenterprise@gmail.com
    networks:
      - web   
    depends_on:
      - mysql

networks:
  web:
    external: true
